### PR TITLE
Add missing trigger history for failed steps to fix #129 

### LINKED ISSUE #129: Missing step details for the failed steps
When you view run details for an errored workflow or failed workflow on the workflow history page, the failed step details are missing.

errored at step 4 

image

but there are no details for step 4  

image

### PR DESCRIPTION
**Pull request by dmitriim**

### CODE REVIEW

**Comment by dmitriim** [comment]
tests are failing from 3.11 due to phpunit update. Needs to be fixed in separate PR.

**Comment by dmitriim** [comment]
with this patch 

image

image

**Comment by Peterburnett** [comment]
How does the parent status page look? I wonder if the count for some of the status' will be broken, might need to be adjusted by 1 in the renderer potentially

**Comment by dmitriim** [comment]
Looks ok in my case. I'm not sure what you mean here.

image

**Comment by Peterburnett** [comment]
Looks fine, I think I confused myself, at one point the 'Errored step 4' was based on the last step success + 1, but when I added failing I moved over to explicit fields for the statuses. Happy to merge!

**Pull request merged**
