### PR TITLE
Add an ability to trigger a workflow synchronously to fix #84

### LINKED ISSUE #84: Feature: add an ability to trigger a workflow synchronously
Add an ability to trigger a workflow synchronously when event happened. 
Probably a new checkbox in the Workflow form.

### PR DESCRIPTION
**Pull request by dmitriim**

### CODE REVIEW

**Comment by dmitriim** [comment]
@mattporritt  thanks for your time. I'd leave parameter hinting and return type hinting  for a new issue and fix it everywhere in the code at once and since then make it as a checklist point for all incoming code. I'll fix "Use constants instead of integers for switches in SQL statements. e.g. NOT_REALTIME instead of 0"

 _If you have a couple of realtime workflows tied to a single event, things could get real bad for the user real fast._

Do you think we should limit a number of real time workflows by an event?

**Comment by mattporritt** [comment]
"Do you think we should limit a number of real time workflows by an event?" - I think that will be overkill, you could still makes things bad with one nasty workflow.  
We'll just put it in the category of Admins can break things

**Comment by dmitriim** [comment]
@mattporritt Actually let's make a new issue to replace all hard coded values at once  e.g. enabled

**Comment by dmitriim** [comment]
Created https://github.com/catalyst/moodle-tool_trigger/issues/91 and https://github.com/catalyst/moodle-tool_trigger/issues/92

**Pull request merged**
